version: "3.7"

services:
  postgres:
    image: docker.io/postgres:15.4-alpine
    container_name: "sales-management-db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sales-management
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
