const products = [
  {
    name: 'Smartphone Galaxy S22',
    description:
      'Un smartphone Android puissant avec un appareil photo de pointe',
    image: 'https://example.com/images/galaxy_s22.jpg',
    price: 799.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Ordinateur portable Dell XPS 15',
    description:
      'Un ordinateur portable haut de gamme avec un écran 4K et un processeur rapide',
    image: 'https://example.com/images/dell_xps_15.jpg',
    price: 1499.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'TV OLED LG 55 pouces',
    description:
      "Une télévision OLED de 55 pouces avec une qualité d'image exceptionnelle",
    image: 'https://example.com/images/lg_oled_tv.jpg',
    price: 1199.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Casque audio Sony WH-1000XM4',
    description:
      'Un casque audio sans fil avec suppression de bruit et une qualité sonore exceptionnelle',
    image: 'https://example.com/images/sony_wh_1000xm4.jpg',
    price: 299.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Console de jeu PlayStation 5',
    description:
      'La dernière console de jeu de Sony avec des graphismes de pointe',
    image: 'https://example.com/images/ps5.jpg',
    price: 499.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Lave-linge Samsung EcoBubble',
    description:
      'Un lave-linge économe en énergie avec des fonctionnalités avancées',
    image: 'https://example.com/images/samsung_ecobubble.jpg',
    price: 599.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Réfrigérateur Whirlpool 500 litres',
    description: 'Un réfrigérateur spacieux avec un compartiment congélateur',
    image: 'https://example.com/images/whirlpool_fridge.jpg',
    price: 799.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Aspirateur Dyson V11',
    description:
      'Un aspirateur sans fil puissant avec une grande autonomie de batterie',
    image: 'https://example.com/images/dyson_v11.jpg',
    price: 399.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Tablette Apple iPad Pro',
    description:
      'Une tablette haut de gamme avec un écran Retina et une puce A14',
    image: 'https://example.com/images/ipad_pro.jpg',
    price: 799.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Appareil photo Nikon D850',
    description:
      'Un appareil photo reflex numérique professionnel avec une résolution élevée',
    image: 'https://example.com/images/nikon_d850.jpg',
    price: 1999.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Smart TV Samsung 65 pouces',
    description:
      'Une Smart TV avec une résolution 4K et des applications intégrées',
    image: 'https://example.com/images/samsung_smart_tv.jpg',
    price: 999.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Machine à café Nespresso Vertuo',
    description:
      'Une machine à café automatique qui prépare une variété de cafés',
    image: 'https://example.com/images/nespresso_vertuo.jpg',
    price: 199.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Console Xbox Series X',
    description:
      'Une console de jeu Xbox puissante avec une vitesse de chargement rapide',
    image: 'https://example.com/images/xbox_series_x.jpg',
    price: 549.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Enceinte Bluetooth JBL Charge 5',
    description: 'Une enceinte portable étanche avec une batterie longue durée',
    image: 'https://example.com/images/jbl_charge_5.jpg',
    price: 129.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Aspirateur robot iRobot Roomba 980',
    description:
      'Un aspirateur robot intelligent pour le nettoyage automatique',
    image: 'https://example.com/images/roomba_980.jpg',
    price: 499.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Machine à laver la vaisselle Bosch Serie 6',
    description:
      'Un lave-vaisselle silencieux avec plusieurs programmes de lavage',
    image: 'https://example.com/images/bosch_dishwasher.jpg',
    price: 699.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Montre intelligente Apple Watch Series 7',
    description:
      'Une montre intelligente avec un écran toujours allumé et de nombreuses fonctionnalités',
    image: 'https://example.com/images/apple_watch_series_7.jpg',
    price: 399.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Table de cuisson à induction Siemens 5 feux',
    description: 'Une table de cuisson à induction avec commandes tactiles',
    image: 'https://example.com/images/siemens_induction_cooktop.jpg',
    price: 899.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Imprimante HP LaserJet Pro',
    description:
      'Une imprimante laser rapide et compacte pour un usage domestique',
    image: 'https://example.com/images/hp_laserjet_pro.jpg',
    price: 299.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Système de son Bose SoundTouch 300',
    description:
      'Un système de son de haute qualité avec une connectivité sans fil',
    image: 'https://example.com/images/bose_soundtouch_300.jpg',
    price: 699.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Machine à laver le linge LG TurboWash',
    description:
      'Une machine à laver le linge efficace avec une capacité de charge importante',
    image: 'https://example.com/images/lg_turbowash_washer.jpg',
    price: 649.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Aspirateur balai Shark DuoClean',
    description:
      'Un aspirateur balai polyvalent avec une technologie de nettoyage avancée',
    image: 'https://example.com/images/shark_duoclean.jpg',
    price: 349.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Réfrigérateur-congélateur Hisense 400 litres',
    description:
      'Un réfrigérateur-congélateur spacieux avec une technologie de refroidissement avancée',
    image: 'https://example.com/images/hisense_fridge_freezer.jpg',
    price: 799.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Cafetière filtre Philips',
    description: 'Une cafetière filtre programmable avec une carafe en verre',
    image: 'https://example.com/images/philips_coffee_maker.jpg',
    price: 59.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Enceinte intelligente Amazon Echo Dot',
    description:
      "Une enceinte intelligente avec l'assistant vocal Alexa intégré",
    image: 'https://example.com/images/amazon_echo_dot.jpg',
    price: 49.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Aspirateur à main Black+Decker',
    description: 'Un aspirateur à main compact pour les petits nettoyages',
    image: 'https://example.com/images/black_and_decker_handheld_vacuum.jpg',
    price: 39.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Montre connectée Garmin Fenix 6X',
    description:
      'Une montre de sport GPS avec des fonctionnalités avancées pour la randonnée et le fitness',
    image: 'https://example.com/images/garmin_fenix_6x.jpg',
    price: 599.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Réfrigérateur américain Samsung',
    description:
      "Un réfrigérateur américain élégant avec un distributeur d'eau et de glaçons",
    image: 'https://example.com/images/samsung_american_fridge.jpg',
    price: 1499.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Ordinateur de bureau HP Pavilion',
    description:
      'Un ordinateur de bureau polyvalent pour le travail et le divertissement',
    image: 'https://example.com/images/hp_pavilion_desktop.jpg',
    price: 799.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Machine à expresso De'Longhi",
    description: 'Une machine à expresso automatique pour les amateurs de café',
    image: 'https://example.com/images/delonghi_espresso_machine.jpg',
    price: 399.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Console de jeu Nintendo Switch',
    description:
      "La console de jeu portable de Nintendo pour jouer n'importe où",
    image: 'https://example.com/images/nintendo_switch.jpg',
    price: 299.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Écouteurs sans fil Bose QuietComfort',
    description:
      'Des écouteurs sans fil avec annulation de bruit pour une expérience audio immersive',
    image: 'https://example.com/images/bose_quietcomfort_earbuds.jpg',
    price: 249.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Laptop convertible Lenovo Yoga 9',
    description:
      'Un laptop convertible avec un écran tactile et une grande autonomie de batterie',
    image: 'https://example.com/images/lenovo_yoga_9.jpg',
    price: 1199.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Téléphone fixe Panasonic KX-TG6822',
    description: 'Un téléphone fixe sans fil avec répondeur intégré',
    image: 'https://example.com/images/panasonic_phone.jpg',
    price: 69.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Climatiseur Daikin Inverter',
    description:
      'Un climatiseur mural avec technologie Inverter pour une efficacité énergétique',
    image: 'https://example.com/images/daikin_air_conditioner.jpg',
    price: 899.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Four à micro-ondes Sharp 25 litres',
    description:
      'Un four à micro-ondes compact avec plusieurs programmes de cuisson',
    image: 'https://example.com/images/sharp_microwave.jpg',
    price: 129.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Drone DJI Mavic Air 2',
    description:
      'Un drone pliable avec une caméra 4K pour des prises de vue aériennes',
    image: 'https://example.com/images/dji_mavic_air_2.jpg',
    price: 799.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Console de jeu Xbox Series S',
    description:
      'Une console de jeu Xbox plus compacte avec une grande puissance',
    image: 'https://example.com/images/xbox_series_s.jpg',
    price: 299.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Enceinte intelligente Google Nest Mini',
    description:
      "Une enceinte intelligente avec l'assistant vocal Google Assistant",
    image: 'https://example.com/images/google_nest_mini.jpg',
    price: 49.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Machine à glaçons Frigidaire',
    description:
      'Une machine à glaçons portable pour préparer des glaçons rapidement',
    image: 'https://example.com/images/frigidaire_ice_maker.jpg',
    price: 99.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Balai vapeur Bissell PowerFresh',
    description: 'Un balai vapeur pour un nettoyage en profondeur des sols',
    image: 'https://example.com/images/bissell_powerfresh.jpg',
    price: 89.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Enregistreur audio Zoom H5',
    description:
      'Un enregistreur audio portable pour des enregistrements de haute qualité',
    image: 'https://example.com/images/zoom_h5.jpg',
    price: 299.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Machine à pop-corn Popcorn Time',
    description: 'Une machine à pop-corn pour les soirées cinéma à la maison',
    image: 'https://example.com/images/popcorn_time_machine.jpg',
    price: 39.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Lampe de bureau Philips Hue',
    description: 'Une lampe de bureau intelligente avec éclairage LED réglable',
    image: 'https://example.com/images/philips_hue_desk_lamp.jpg',
    price: 79.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Tondeuse à gazon Honda HRX217',
    description: 'Une tondeuse à gazon autotractée avec une lame en acier',
    image: 'https://example.com/images/honda_lawn_mower.jpg',
    price: 499.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Lisseur à cheveux GHD Platinum+',
    description: 'Un lisseur à cheveux de qualité professionnelle',
    image: 'https://example.com/images/ghd_hair_straightener.jpg',
    price: 199.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Machine à pain Panasonic SD-YR2500',
    description: 'Une machine à pain pour préparer du pain frais à la maison',
    image: 'https://example.com/images/panasonic_bread_maker.jpg',
    price: 149.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Lecteur Blu-ray Sony UBP-X700',
    description: 'Un lecteur Blu-ray 4K avec prise en charge du HDR',
    image: 'https://example.com/images/sony_blu-ray_player.jpg',
    price: 149.99,
    warranty_duration: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Roborock S7 Robot Vacuum',
    description: 'Un aspirateur robot haut de gamme avec fonction de lavage',
    image: 'https://example.com/images/roborock_s7.jpg',
    price: 599.99,
    warranty_duration: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Casque de réalité virtuelle Oculus Quest 2',
    description:
      'Un casque de réalité virtuelle pour des expériences immersives',
    image: 'https://example.com/images/oculus_quest_2.jpg',
    price: 299.99,
    warranty_duration: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

module.exports = products;
